DOMAIN = "https://api.coingecko.com/"
CURRENCY_API = "api/v3/simple/supported_vs_currencies"
TOKEN_PLATFORM_API = "api/v3/coins/list"
TOKEN_ETHEREUM_PRICE_API = "api/v3/simple/token_price/ethereum"
TOKEN_ETHEREUM_PRICE_API_DAILY = "api/v3/coins/replacing_id/ohlc"
MARKET_API = "api/v3/coins/ethereum/market_chart"